### ISSUE TITLE
Insecure Browser Detected!

### ISSUE THREAD

**Issue by danpmohn** [DataHenHQ/till#8] opened 2021-08-24 17:29 UTC
At the site below, I am using puppeteer through till.  Till is started with the command;

till serve --proxy-file c:\temp\till\proxylist.txt --token <mytoken>--force-user-agent --ua-type desktop 

https://secure.utah.gov/llv/search/index.html

Insecure Browser Detected! 
We noticed that your browser is REALLY OLD.

Let me know if there is additional information I can provide to help debug.

Info:
Cache	MISS
RID	01FDWJ3NMJK05AZM77M50DGTHS
GID	secure.utah.gov-08228751e1bab3b452a3e0d6830a1e50
SID	
Timestamp	2021-08-24 13:07:45
 
Config:
ForceUA	true
UaType	desktop
UseProxy	true
StickyCookies	true
StickyUA	true
IgnoreInterceptors	[]
IgnoreAllInterceptors	false
CacheFreshness	now
CacheServeFailures	false
 
Request:
Method	POST
URL	https://secure.utah.gov/llv/search/index.html
Header	
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding	gzip, deflate, br
Accept-Language	en-US
Cache-Control	no-cache
Connection	keep-alive
Content-Length	573
Content-Type	application/x-www-form-urlencoded
Cookie	JSESSIONID=997DA0A8AD40B2C1AB70B5B556A1E845; TS01bdb7d2=0143bf51700840319b0a08eeb8fbe8681009410c51139c8d6e58c60496aabe65498495e0a8af296ef0edd92ba99bd801c0a1857f32b92dcf6a887da12f8c350179f47b9356; TS01959f26=0143bf5170adbfef85245e0b4e92afb875bb8f3992139c8d6e58c60496aabe65498495e0a8edfd3d3b396fd57ee8cec40e757bb731; __utma=128287630.704573828.1629824827.1629824827.1629824827.1; __utmc=128287630; __utmz=128287630.1629824827.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1; fontsize=90%25; _ga=GA1.2.704573828.1629824827; _gid=GA1.2.1327052485.1629824827; _gat_UA-103830962-11=1; __utmb=128287630.2.9.1629824865296
Origin	https://secure.utah.gov
Pragma	no-cache
Referer	https://secure.utah.gov/llv/search/index.html
Sec-Fetch-Dest	document
Sec-Fetch-Mode	navigate
Sec-Fetch-Site	same-origin
Sec-Fetch-User	?1
Upgrade-Insecure-Requests	1
User-Agent	Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
ContentLength	573
Body	g-recaptcha-response=03AGdBq25ElbcQolMLQOZ3PnpAWF7Tvqhe55PBHrAp1oWqRWEQyBdlZquRQa5rXaucm4CiAxyZR7roFzAQsWJjjzesc_br5Sywr21DVfYyDNCjHEbGYorI3fsPOgxmijW0p9TJZGLtiaZmBVE9J4MeOZxGrUD9NQSR517qnmphipvyOqODKOPESQwcKoYOLDIaNsA4PWOMsbj2EnKZZc4j-79W5FBPT5hDmnyfgSNLcW7VFSQ73O5muE_jybf0LvgyWKKtaKexuIK_lLwjt44qXAzz7xoG2ruafB6N7xo2vrUoplhQ394iSeO7chDN47QlbI_4x1SIq0f0g5KRxVN9GYuCgPsCRCc547f6HkigwK-BZueHD8eSVG2YglwxL7vvUHj_eXHml2_gdHUVwp_Gk9QJdeFnM6vfPKDxpEqMgcjdH8IBzqxJmzo&licenseNumberCore=339473&licenseNumberFourDigit=5518&type=by_number&_csrf=e92e3abe-4aab-4843-87d4-bbbd87d4b879
 
Response:
Status	200 OK
Proto	HTTP/1.1
Header	
Accept-Ranges	bytes
Connection	Keep-Alive
Content-Length	17488
Content-Type	text/html; charset=UTF-8
Date	Tue, 24 Aug 2021 17:07:46 GMT
Keep-Alive	timeout=5, max=100
Server	Apache
Strict-Transport-Security	max-age=16070400; includeSubDomains
ContentLength	17488

**Comment by colorfulsing** [comment] 2021-08-25 16:38
@paramaw I will assign this issue to myself and take a loo, it might be caused by an the old browser config at the user agent config file.

**Closed** 2021-09-02 14:49 UTC
Labels: enhancement
